### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Artucuno** [Catalyst4222/interactions-checks#5]
```py
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from interactions.ext.checks import check
  File "/usr/local/lib/python3.8/dist-packages/interactions/ext/checks/__init__.py", line 8, in <module>
    from .cooldown import *
  File "/usr/local/lib/python3.8/dist-packages/interactions/ext/checks/cooldown. py", line 10, in <module>
    class Bucket:
  File "/usr/local/lib/python3.8/dist-packages/interactions/ext/checks/cooldown.py", line 37, in Bucket
    def _get_times(self, ctx) -> list[float]:
TypeError: 'type' object is not subscriptable
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f62d5274550>
```
I just installed the module

**Comment by Catalyst4222** [comment]
Should be fixed as of [1b566fc](https://github.com/Catalyst4222/interactions-checks/commit/1b566fc80be9ce9a67ca38f63c2f268b29da32ca), can you confirm?
