### ISSUE TITLE
AttributeError: 'utills' object has no attribute 'guild_id'

### ISSUE THREAD

**Issue by pgrd1** [Catalyst4222/interactions-checks#7]
```
future: <Task finished name='Task-29' coro=<utills.developer() done, defined at c:\Users\interactions\client\models\command.py:930> exception=AttributeError("'utills' object has no attribute 'guild_id'")>
Traceback (most recent call last):
  File "c:\Users\interactions\client\models\command.py", line 970, in wrapper
    raise e
  File "c:\Users\interactions\client\models\command.py", line 938, in wrapper
    return await coro(self.extension, ctx, *args, **kwargs)
  File "c:\Users\interactions\ext\checks\cooldown.py", line 88, in new_func
    if bucket.can_run(ctx):
  File "c:\Users\interactions\ext\checks\cooldown.py", line 63, in can_run
    timers = self._get_times(ctx)
  File "c:\Users\interactions\ext\checks\cooldown.py", line 42, in _get_times
    key = getattr(ctx, "guild_id")
    ```

**Comment by Catalyst4222** [comment]
Can you send the code causing the error?
