### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by rahul-nanwani** [Catalyst4222/interactions-checks#9]
I got the below error when I tried to import as shown in the examples

```python-traceback
Traceback (most recent call last):
  File "D:\Users\Projects\bot.py", line 2, in <module>
    from interactions.ext.checks import check, setup
  File "D:\Users\Projects\venv\lib\site-packages\interactions\ext\checks\__init__.py", line 6, in <module>
    from .checks import *  # noqa: F401 F403
  File "D:\Users\Projects\venv\lib\site-packages\interactions\ext\checks\checks.py", line 6, in <module>
    from . import CheckFailure, errors
ImportError: cannot import name 'CheckFailure' from partially initialized module 'interactions.ext.checks' (most likely due to a circular import) (D:\Users\Projects\venv\lib\site-packages\interactions\ext\checks\__init__.py)
```

**Comment by rahul-nanwani** [comment]
PR: https://github.com/Catalyst4222/interactions-checks/pull/10
